export interface LocationData {
  country: string
  states: string[]
  postalCodePattern: string
  postalCodePlaceholder: string
}

export const LATAM_LOCATIONS: Record<string, LocationData> = {
  'Colombia': {
    country: 'Colombia',
    states: [
      'Amazonas',
      'Antioquia',
      'Arauca',
      'Atlántico',
      'Bolívar',
      'Boyacá',
      'Caldas',
      'Caquetá',
      'Casanare',
      'Cauca',
      'Cesar',
      'Chocó',
      'Córdoba',
      'Cundinamarca',
      'Guainía',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Nariño',
      'Norte de Santander',
      'Putumayo',
      'Quindío',
      'Risaralda',
      'San Andrés y Providencia',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupés',
      'Vichada'
    ],
    postalCodePattern: '^\\d{6}$',
    postalCodePlaceholder: '110111'
  },
  'Brazil': {
    country: 'Brazil',
    states: [
      'Acre',
      'Alagoas',
      'Amapá',
      'Amazonas',
      'Bahia',
      'Ceará',
      'Distrito Federal',
      'Espírito Santo',
      'Goiás',
      'Maranhão',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Pará',
      'Paraíba',
      'Paraná',
      'Pernambuco',
      'Piauí',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondônia',
      'Roraima',
      'Santa Catarina',
      'São Paulo',
      'Sergipe',
      'Tocantins'
    ],
    postalCodePattern: '^\\d{5}-?\\d{3}$',
    postalCodePlaceholder: '01310-100'
  },
  'Mexico': {
    country: 'Mexico',
    states: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Coahuila',
      'Colima',
      'Ciudad de México',
      'Durango',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'México',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas'
    ],
    postalCodePattern: '^\\d{5}$',
    postalCodePlaceholder: '01000'
  },
  'Argentina': {
    country: 'Argentina',
    states: [
      'Buenos Aires',
      'Catamarca',
      'Chaco',
      'Chubut',
      'Ciudad Autónoma de Buenos Aires',
      'Córdoba',
      'Corrientes',
      'Entre Ríos',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquén',
      'Río Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucumán'
    ],
    postalCodePattern: '^[A-Z]?\\d{4}[A-Z]{0,3}$',
    postalCodePlaceholder: 'C1426'
  },
  'Chile': {
    country: 'Chile',
    states: [
      'Arica y Parinacota',
      'Tarapacá',
      'Antofagasta',
      'Atacama',
      'Coquimbo',
      'Valparaíso',
      'Región Metropolitana',
      'O\'Higgins',
      'Maule',
      'Ñuble',
      'Biobío',
      'La Araucanía',
      'Los Ríos',
      'Los Lagos',
      'Aysén',
      'Magallanes'
    ],
    postalCodePattern: '^\\d{7}$',
    postalCodePlaceholder: '8320000'
  },
  'Peru': {
    country: 'Peru',
    states: [
      'Amazonas',
      'Áncash',
      'Apurímac',
      'Arequipa',
      'Ayacucho',
      'Cajamarca',
      'Callao',
      'Cusco',
      'Huancavelica',
      'Huánuco',
      'Ica',
      'Junín',
      'La Libertad',
      'Lambayeque',
      'Lima',
      'Loreto',
      'Madre de Dios',
      'Moquegua',
      'Pasco',
      'Piura',
      'Puno',
      'San Martín',
      'Tacna',
      'Tumbes',
      'Ucayali'
    ],
    postalCodePattern: '^\\d{5}$',
    postalCodePlaceholder: '15001'
  },
  'Ecuador': {
    country: 'Ecuador',
    states: [
      'Azuay',
      'Bolívar',
      'Cañar',
      'Carchi',
      'Chimborazo',
      'Cotopaxi',
      'El Oro',
      'Esmeraldas',
      'Galápagos',
      'Guayas',
      'Imbabura',
      'Loja',
      'Los Ríos',
      'Manabí',
      'Morona Santiago',
      'Napo',
      'Orellana',
      'Pastaza',
      'Pichincha',
      'Santa Elena',
      'Santo Domingo de los Tsáchilas',
      'Sucumbíos',
      'Tungurahua',
      'Zamora Chinchipe'
    ],
    postalCodePattern: '^\\d{6}$',
    postalCodePlaceholder: '170150'
  },
  'Uruguay': {
    country: 'Uruguay',
    states: [
      'Artigas',
      'Canelones',
      'Cerro Largo',
      'Colonia',
      'Durazno',
      'Flores',
      'Florida',
      'Lavalleja',
      'Maldonado',
      'Montevideo',
      'Paysandú',
      'Río Negro',
      'Rivera',
      'Rocha',
      'Salto',
      'San José',
      'Soriano',
      'Tacuarembó',
      'Treinta y Tres'
    ],
    postalCodePattern: '^\\d{5}$',
    postalCodePlaceholder: '11000'
  },
  'Costa Rica': {
    country: 'Costa Rica',
    states: [
      'San José',
      'Alajuela',
      'Cartago',
      'Heredia',
      'Guanacaste',
      'Puntarenas',
      'Limón'
    ],
    postalCodePattern: '^\\d{5}$',
    postalCodePlaceholder: '10101'
  },
  'Panama': {
    country: 'Panama',
    states: [
      'Bocas del Toro',
      'Chiriquí',
      'Coclé',
      'Colón',
      'Darién',
      'Herrera',
      'Los Santos',
      'Panamá',
      'Panamá Oeste',
      'Veraguas',
      'Emberá-Wounaan',
      'Guna Yala',
      'Ngäbe-Buglé'
    ],
    postalCodePattern: '^\\d{4}$',
    postalCodePlaceholder: '0801'
  },
  'Dominican Republic': {
    country: 'Dominican Republic',
    states: [
      'Distrito Nacional',
      'Azua',
      'Baoruco',
      'Barahona',
      'Dajabón',
      'Duarte',
      'Elías Piña',
      'El Seibo',
      'Espaillat',
      'Hato Mayor',
      'Hermanas Mirabal',
      'Independencia',
      'La Altagracia',
      'La Romana',
      'La Vega',
      'María Trinidad Sánchez',
      'Monseñor Nouel',
      'Monte Cristi',
      'Monte Plata',
      'Pedernales',
      'Peravia',
      'Puerto Plata',
      'Samaná',
      'San Cristóbal',
      'San José de Ocoa',
      'San Juan',
      'San Pedro de Macorís',
      'Sánchez Ramírez',
      'Santiago',
      'Santiago Rodríguez',
      'Santo Domingo',
      'Valverde'
    ],
    postalCodePattern: '^\\d{5}$',
    postalCodePlaceholder: '10100'
  },
  'United States': {
    country: 'United States',
    states: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming'
    ],
    postalCodePattern: '^\\d{5}(-\\d{4})?$',
    postalCodePlaceholder: '10001'
  },
  'Canada': {
    country: 'Canada',
    states: [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Newfoundland and Labrador',
      'Northwest Territories',
      'Nova Scotia',
      'Nunavut',
      'Ontario',
      'Prince Edward Island',
      'Quebec',
      'Saskatchewan',
      'Yukon'
    ],
    postalCodePattern: '^[A-Z]\\d[A-Z]\\s?\\d[A-Z]\\d$',
    postalCodePlaceholder: 'M5H 2N2'
  }
}

export const COUNTRY_LIST = Object.keys(LATAM_LOCATIONS).sort()

export function getStatesForCountry(country: string): string[] {
  return LATAM_LOCATIONS[country]?.states || []
}

export function getPostalCodeInfo(country: string): { pattern: string; placeholder: string } {
  const location = LATAM_LOCATIONS[country]
  return {
    pattern: location?.postalCodePattern || '^[A-Za-z0-9\\s-]+$',
    placeholder: location?.postalCodePlaceholder || '00000'
  }
}
