import { motion } from 'framer-motion'
import { Card, CardContent } from './ui/card'
import { Badge } from './ui/badge'
import { Sparkle, TrendDown, Shield, Lightning, Pulse, ChartLine } from '@phosphor-icons/react'
import { useState } from 'react'
import { mockProducts } from '../lib/mockData'

export function AgingSection({ onProductClick }: { onProductClick?: (product: typeof mockProducts[0]) => void } = {}) {
  const [expandedCard, setExpandedCard] = useState<string | null>(null)

  const mechanismCards = [
    {
      id: 'retinol',
      icon: <Pulse className="w-8 h-8" />,
      title: 'Retinoids/Bakuchiol',
      subtitle: 'Cellular Renewal Engine',
      description: 'Accelerate keratinocyte turnover, stimulate collagen I/III synthesis, and refine pores and texture while CBD reduces the irritation cascade.',
      details: 'Retinoids bind to nuclear retinoic acid receptors (RARs) to upregulate genes responsible for collagen production and cell differentiation. By accelerating the 28-day epidermal turnover cycle, they effectively "resurface" skin from within, revealing fresher, younger cells while improving texture and tone. Bakuchiol offers a gentler alternative through different pathways, activating collagen synthesis without the photosensitivity or irritation typical of retinoids.',
      mechanism: [
        'Upregulates collagen I and III gene expression in dermal fibroblasts',
        'Inhibits matrix metalloproteinases (MMPs) that degrade collagen',
        'Normalizes keratinization to refine texture and minimize pores',
        'Reduces hyperpigmentation by inhibiting tyrosinase activity',
        'MTRX-CBD buffers irritation, allowing consistent use for maximum results'
      ],
      gradient: 'from-[oklch(0.65_0.12_200)] to-[oklch(0.50_0.12_230)]'
    },
    {
      id: 'peptides',
      icon: <Sparkle className="w-8 h-8" />,
      title: 'Peptides',
      subtitle: 'Structural Architects',
      description: 'Signal fibroblasts to rebuild collagen and elastin networks, improving firmness and snap‑back over time.',
      details: 'These peptides are a synergistic blend of palmitoyl oligopeptide and palmitoyl tetrapeptide-7. These short-chain peptides mimic the breakdown fragments of collagen and elastin, "tricking" fibroblasts into believing the matrix is damaged. This triggers a repair response, boosting production of collagen types I, III, and IV, as well as elastin and hyaluronic acid.',
      mechanism: [
        'Mimics natural skin repair signals to activate fibroblast synthesis',
        'Increases collagen I production by up to 350% in controlled studies',
        'Boosts collagen III and IV for comprehensive matrix reinforcement',
        'Enhances elastin synthesis for improved skin resilience and "bounce"',
        'Reduces micro-inflammation (IL-6) that degrades newly formed collagen',
        'Works synergistically with CBD to create an optimal repair environment'
      ],
      gradient: 'from-[oklch(0.70_0.14_290)] to-[oklch(0.60_0.18_270)]'
    },
    {
      id: 'antioxidants',
      icon: <Shield className="w-8 h-8" />,
      title: 'Antioxidants',
      subtitle: 'Vitamin C / Resveratrol',
      description: 'Neutralize free radicals that drive collagen fragmentation and pigment clustering.',
      details: 'Free radicals are unstable molecules generated by UV exposure, pollution, and metabolic stress. They steal electrons from healthy cells, causing oxidative damage to lipids, proteins, and DNA. This oxidative stress is a primary driver of collagen degradation, hyperpigmentation, and cellular aging.',
      mechanism: [
        'Vitamin C (MAP): Stable, non-irritating form that brightens and boosts collagen synthesis',
        'Neutralizes singlet oxygen and hydroxyl radicals generated by UV exposure',
        'Inhibits tyrosinase to prevent melanin formation and reduce manchas',
        'Resveratrol: Activates SIRT1 longevity genes for cellular preservation',
        'Protects against lipid peroxidation that causes membrane damage',
        'Works synergistically: antioxidants enhance each other\'s stability and penetration'
      ],
      gradient: 'from-[oklch(0.75_0.15_40)] to-[oklch(0.65_0.12_20)]'
    },
    {
      id: 'barrier',
      icon: <Lightning className="w-8 h-8" />,
      title: 'Barrier Support',
      subtitle: 'Ceramides & Hyaluronic Acid',
      description: 'Keep the barrier resilient so anti‑aging actives can be used regularly without chronic micro‑damage.',
      details: 'A strong barrier is the foundation of effective anti-aging. Without it, even the best actives can cause irritation, inflammation, and paradoxical damage. Ceramides and HA work together to maintain barrier integrity while ensuring optimal hydration.',
      mechanism: [
        'Ceramides 3:1:1 ratio rebuilds the lipid matrix between corneocytes',
        'Reduces transepidermal water loss (TEWL) by 28% in 4 weeks',
        'Multi-weight HA: surface hydration + deep dermal plumping',
        'HA holds 1000x its weight in water for lasting hydration',
        'Strong barrier allows consistent use of potent actives without irritation',
        'Prevents "inflammaging" caused by chronic barrier compromise'
      ],
      gradient: 'from-[oklch(0.60_0.10_210)] to-[oklch(0.75_0.08_210)]'
    }
  ]

  const agingTimeline = [
    { age: '20s', collagen: '100%', description: 'Peak collagen production, optimal skin resilience and regeneration' },
    { age: '25', collagen: '95%', description: 'Collagen decline begins (~1% per year), still highly responsive to intervention' },
    { age: '30', collagen: '90%', description: 'First subtle signs may appear, prevention strategies show maximum ROI' },
    { age: '35', collagen: '85%', description: 'Early lines may become visible, transition from prevention to correction' },
    { age: '40', collagen: '80%', description: 'Loss of 20% structural support, visible changes in firmness and texture' }
  ]

  const recommendedProducts = [
    {
      id: 'mtrx-002',
      name: 'The Time Bender',
      formula: '8.0% MTRX-CBD + Retinol',
      benefit: 'The gold standard for wrinkles. Accelerates renewal while CBD buffers irritation for consistent use.'
    },
    {
      id: 'mtrx-004',
      name: 'The Architect',
      formula: '8.0% MTRX-CBD + Polypeptides',
      benefit: 'Rebuilds collagen and elastin networks. Improves firmness and structural integrity over time.'
    },
    {
      id: 'mtrx-001',
      name: 'The Harmonizer',
      formula: '8.0% MTRX-CBD',
      benefit: 'Establishes the foundation for the entire MTRX protocol. Silences inflammation and creates a peaceful canvas for all other actives.'
    },
    {
      id: 'mtrx-006',
      name: 'The Spark',
      formula: '8.0% MTRX-CBD + Coenzyme Q10',
      benefit: 'Reignites cellular energy. Reduces fatigue signs and supports mitochondrial collagen synthesis.'
    },
    {
      id: 'mtrx-010',
      name: 'The Rainmaker',
      formula: '8.0% MTRX-CBD + Hyaluronic Acid',
      benefit: 'Floods skin with multi-weight hydration and locks it in, as CBD supports barrier function to prevent the "flash-drying" effect of standalone HA.'
    },
    {
      id: 'mtrx-011',
      name: 'The Mason',
      formula: '8.0% MTRX-CBD + Ceramides',
      benefit: 'Rebuilds the lipid "mortar" of the barrier; CBD helps soothe over-treated or sensitized skin so barrier repair can progress without flare-ups.'
    },
    {
      id: 'mtrx-008',
      name: 'The Naturalist',
      formula: '8.0% MTRX-CBD + Bakuchiol',
      benefit: 'Delivers retinol-style smoothing and evening with a gentler, day-friendly profile, while CBD adds an extra tolerance buffer for sensitive or first-time users.'
    }
  ]

  return (
    <div className="bg-gradient-to-br from-background via-[oklch(0.96_0.01_230)] to-[oklch(0.94_0.02_240)] py-16">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <Badge className="mb-4 text-sm px-4 py-1.5 bg-primary/10 text-primary border-primary/20">
              SKIN CONDITION
            </Badge>
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-slate-dark mb-6">
              AGING
            </h1>
            <p className="text-2xl md:text-3xl text-primary font-semibold mb-6">
              Rewrite Time, Don't Fight It
            </p>
            <div className="max-w-4xl mx-auto">
              <p className="text-lg md:text-xl text-gray-medium leading-relaxed mb-8">
                Aging is a cumulative systems change in skin—collagen loss, elastin fatigue, slower turnover, 
                and chronic micro‑inflammation—not just "wrinkles on the surface." Supporting the matrix early 
                means preserving structure, not chasing damage later.
              </p>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="mb-16"
          >
            <Card className="bg-gradient-to-br from-[oklch(0.98_0.005_230)] to-[oklch(0.96_0.01_240)] border-primary/20 shadow-lg">
              <CardContent className="p-8 md:p-12">
                <h2 className="text-3xl md:text-4xl font-bold text-slate-dark mb-6">
                  The Biology of Structural Aging
                </h2>
                <div className="prose prose-lg max-w-none">
                  <p className="text-gray-medium leading-relaxed mb-6">
                    Collagen production peaks in the early 20s and then declines by roughly <strong>1% per year</strong>, 
                    so by 40 many people have lost around a fifth of their dermal support. Micro‑movements, UV exposure, 
                    pollution, and sugar‑driven glycation gradually stiffen collagen and thin the dermis, leading to 
                    etched expression lines, laxity, and visible fatigue.
                  </p>
                  <p className="text-gray-medium leading-relaxed mb-6">
                    <strong>Prejuvenation</strong> means intervening while the architecture is 
                    still responsive: supporting fibroblasts, defending against oxidative stress, and smoothing early 
                    texture changes before they evolve into fixed folds.
                  </p>
                  <p className="text-gray-medium leading-relaxed">
                    MTRX's anti‑aging axis combines <strong>retinoids and bakuchiol</strong> for turnover and collagen 
                    signaling, <strong>peptides</strong> for structural reinforcement, and <strong>MTRX-CBD</strong> to 
                    buffer the inflammatory "cost" of these strong actives so users can stay consistent without peeling, 
                    burning, or dropping the routine.
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="mb-16"
          >
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-slate-dark mb-4">
                The Collagen Decline Timeline
              </h2>
              <p className="text-gray-medium text-lg">
                Understanding when and why intervention matters most
              </p>
            </div>

            <div className="relative">
              <div className="absolute left-8 top-0 bottom-0 w-0.5 bg-gradient-to-b from-primary via-accent to-primary/20" />
              
              <div className="space-y-8">
                {agingTimeline.map((stage, index) => (
                  <motion.div
                    key={stage.age}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.5, delay: 0.3 + index * 0.1 }}
                    className="relative pl-24"
                  >
                    <div className="absolute left-0 top-0 w-16 h-16 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center shadow-lg">
                      <span className="text-white font-bold text-sm">{stage.age}</span>
                    </div>
                    
                    <Card className="bg-white/80 backdrop-blur-sm border-primary/20 hover:border-primary/40 transition-all duration-300 hover:shadow-xl">
                      <CardContent className="p-6">
                        <div className="flex items-center justify-between mb-3">
                          <h3 className="text-xl font-bold text-slate-dark">
                            {stage.collagen} Collagen Density
                          </h3>
                          <div className="flex items-center gap-2">
                            <div className="w-32 h-3 bg-muted rounded-full overflow-hidden">
                              <motion.div
                                initial={{ width: 0 }}
                                animate={{ width: stage.collagen }}
                                transition={{ duration: 1, delay: 0.5 + index * 0.1 }}
                                className="h-full bg-gradient-to-r from-primary to-accent rounded-full"
                              />
                            </div>
                            <TrendDown className="w-5 h-5 text-primary" />
                          </div>
                        </div>
                        <p className="text-gray-medium leading-relaxed">
                          {stage.description}
                        </p>
                      </CardContent>
                    </Card>
                  </motion.div>
                ))}
              </div>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="mb-16"
          >
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-slate-dark mb-4">
                Mechanism Call-outs
              </h2>
              <p className="text-gray-medium text-lg max-w-3xl mx-auto">
                How MTRX addresses aging at the cellular and molecular level
              </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {mechanismCards.map((card, index) => (
                <motion.div
                  key={card.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: 0.5 + index * 0.1 }}
                >
                  <Card 
                    className={`group relative overflow-hidden border-2 transition-all duration-300 cursor-pointer ${
                      expandedCard === card.id 
                        ? 'border-primary shadow-2xl ring-4 ring-primary/20' 
                        : 'border-primary/20 hover:border-primary/40 hover:shadow-xl'
                    }`}
                    onClick={() => setExpandedCard(expandedCard === card.id ? null : card.id)}
                  >
                    <div className={`absolute inset-0 bg-gradient-to-br ${card.gradient} opacity-5 group-hover:opacity-10 transition-opacity duration-300`} />
                    
                    <CardContent className="relative p-6 md:p-8">
                      <div className="flex items-start gap-4 mb-4">
                        <div className={`flex-shrink-0 w-14 h-14 rounded-xl bg-gradient-to-br ${card.gradient} flex items-center justify-center text-white shadow-lg`}>
                          {card.icon}
                        </div>
                        <div className="flex-1">
                          <h3 className="text-xl md:text-2xl font-bold text-slate-dark mb-1">
                            {card.title}
                          </h3>
                          <p className="text-primary font-semibold text-sm">
                            {card.subtitle}
                          </p>
                        </div>
                        <motion.div
                          animate={{ rotate: expandedCard === card.id ? 180 : 0 }}
                          transition={{ duration: 0.3 }}
                          className="flex-shrink-0"
                        >
                          <ChartLine className={`w-6 h-6 ${expandedCard === card.id ? 'text-primary' : 'text-muted-foreground'}`} />
                        </motion.div>
                      </div>
                      
                      <p className="text-gray-medium leading-relaxed mb-4">
                        {card.description}
                      </p>

                      <motion.div
                        initial={false}
                        animate={{
                          height: expandedCard === card.id ? 'auto' : 0,
                          opacity: expandedCard === card.id ? 1 : 0
                        }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden"
                      >
                        <div className="pt-4 border-t border-primary/10">
                          <p className="text-sm text-gray-medium leading-relaxed mb-4 italic">
                            {card.details}
                          </p>
                          <div className="bg-gradient-to-br from-muted/30 to-muted/10 rounded-lg p-4">
                            <h4 className="font-semibold text-slate-dark mb-3 text-sm uppercase tracking-wide">
                              Molecular Mechanisms:
                            </h4>
                            <ul className="space-y-2">
                              {card.mechanism.map((item, idx) => (
                                <li key={idx} className="flex items-start gap-2 text-sm">
                                  <span className="flex-shrink-0 w-1.5 h-1.5 rounded-full bg-primary mt-1.5" />
                                  <span className="text-slate-dark/80 leading-relaxed">{item}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        </div>
                      </motion.div>

                      <div className="mt-4 text-sm text-primary/60 font-medium">
                        {expandedCard === card.id ? 'Click to collapse' : 'Click to expand'}
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
            className="mb-16"
          >
            <Card className="bg-gradient-to-br from-primary/5 to-accent/5 border-primary/20">
              <CardContent className="p-8 md:p-12">
                <h2 className="text-3xl md:text-4xl font-bold text-slate-dark mb-6 text-center">
                  Emotional Benefit
                </h2>
                <p className="text-xl md:text-2xl text-center text-gray-medium leading-relaxed max-w-4xl mx-auto">
                  AGING is about keeping your features dynamic and expressive while your canvas stays firm, 
                  bright, and resilient—so you <strong className="text-slate-dark">look like yourself longer</strong>.
                </p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.7 }}
          >
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold text-slate-dark mb-4">
                Recommended Products
              </h2>
              <p className="text-gray-medium text-lg">
                The complete anti-aging protocol for prejuvenation
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {recommendedProducts.map((product, index) => {
                const fullProduct = mockProducts.find(p => p.id === product.id)
                
                return (
                  <motion.div
                    key={product.name}
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.5, delay: 0.8 + index * 0.1 }}
                  >
                    <Card 
                      className="group relative overflow-hidden border-2 border-primary/20 hover:border-primary/40 transition-all duration-300 hover:shadow-2xl bg-white cursor-pointer"
                      onClick={() => fullProduct && onProductClick?.(fullProduct)}
                    >
                      <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-accent/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                      
                      <CardContent className="relative p-6">
                        <div className="mb-4">
                          <h3 className="text-xl font-bold text-slate-dark mb-2">
                            {product.name}
                          </h3>
                          <Badge variant="secondary" className="text-xs font-mono">
                            {product.formula}
                          </Badge>
                        </div>
                        <p className="text-gray-medium leading-relaxed">
                          {product.benefit}
                        </p>
                      </CardContent>
                    </Card>
                  </motion.div>
                )
              })}
            </div>
          </motion.div>

        </div>
      </div>
    </div>
  )
}
